spring.application.name=librarymanagementsystem
server.port=8260

spring.datasource.url=jdbc:mysql://localhost:3306/librarymanagementsystem?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=YourNewPassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

